# Generated by Django 4.2.9 on 2024-02-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slurpit_netbox', '0004_slurpitmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='slurpitmapping',
            name='mapping_type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
